### ISSUE TITLE
Beschränkung der Anruferzahl

### ISSUE THREAD

**Issue by kirsey** [rickmer/rephone#2]
Ich denke darüber nach, ob wir die Anzahl von Anrufen auf eine bestimmte Telefonnummer beschränken sollen. Würden nicht 20 Anrufe pro Tag auf eine Nummer ausreichen um die Nachricht zu übermitteln? Aus meiner Sicht sind 100 oder sogar 1000 Anrufe eher ein Telefon-DDos als ein konstruktiver Beitrag zu einem Thema.

**Comment by rickmer** [comment]
Da können wir einen Konfigurationspunkt draus machen. Aber:

da die Anrufe pseudo-zufällig auf alle "Gesprächspartner" verteilt werden, wären das bei max 20 Anrufen pro Tag bereits >= 12000 Anrufe pro Tag. Um einseitige Vorlieben bei der Auswahl der Gesprächspartner zu minimieren könnte man die Zufallsfunktion natürlich so manipulieren dass die Wahrscheinlichkeit für den Vorschlag eines Gesprächspartners mit der Anzahl der - für diesen Gesprächspartner - bereits vermittelten Anrufe sinkt.

**Comment by kirsey** [comment]
Ja, guter Punkt mit der Zufallsfunktion. Ich bin für sinkende Wahrscheinlichkeiten für bereits vermittelte Anrufe.
