### ISSUE TITLE
make install on clean raspbian jessi failed: unrecognized command line option ‘-fstack-protector-strong’

### ISSUE THREAD

**Issue by joewa** [rickmer/rephone#4]
`running build_ext

building 'PIL._imaging' extension

creating build/temp.linux-armv6l-3.4/libImaging

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_LIBZ -I/usr/include/freetype2 -I/tmp/pip-build-jvmwi7hc/Pillow/libImaging -I/home/joerg/repos/rephone/include -I/usr/local/include -I/usr/include -I/usr/include/python3.4m -I/home/joerg/repos/rephone/include/python3.4m -I/usr/include/arm-linux-gnueabihf -c _imaging.c -o build/temp.linux-armv6l-3.4/_imaging.o

cc1: error: unrecognized command line option ‘-fstack-protector-strong’

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
`

**Comment by kirsey** [comment]
Ich glaube, dass bei dir 'make install' noch python2.7 nutzt statt python3.4. 
Gucke mal hier: https://askubuntu.com/questions/320996/make-default-python-command-to-use-python-3

**Comment by joewa** [comment]
Nee, make install holt python3.4 oder bricht ab.
Es geht jetzt: man braucht gcc-4.8, gcc-4.9 oder neuer.
Die Frage ist nur, wie man das "richtig" in apt.list einträgt.`

**Comment by kirsey** [comment]
Wir können "gcc-4.9" als niedrigsten gemeinsamen Standard eintragen. Falls ein System bereits über eine höhere Version verfügt, würde auch nichts neu installiert werden.

**Comment by joewa** [comment]
Habs wieder raus genommen, weil es unter ubuntu LTS kein gcc-4.9 gibt.
Ich schreibe einen Hinweis in die readme.
