### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by kirsey** [rickmer/rephone#5]
**Ich bin auch dabei meinen RaspberryPi aufzusetzen und habe noch ein letztes Problem mit der Firewall. 
Auf dem Raspy erhalte ich:**
sudo ufw status verbose
Status: active
Logging: on (low)
Default: allow (incoming), allow (outgoing)
New profiles: skip

To                         Action      From
--                         ------      ----
22                         ALLOW IN    Anywhere
5001                       ALLOW IN    Anywhere
80                         ALLOW IN    Anywhere
9001                       ALLOW IN    Anywhere
9030                       ALLOW IN    Anywhere
22                         ALLOW IN    Anywhere (v6)
5001                       ALLOW IN    Anywhere (v6)
80                         ALLOW IN    Anywhere (v6)
9001                       ALLOW IN    Anywhere (v6)
9030                       ALLOW IN    Anywhere (v6)

**Aber im eigenen Netzwerk erhalte ich:**
nmap -v 192.168.178.26

Starting Nmap 6.47 ( http://nmap.org ) at 2016-03-24 23:08 CET
Initiating Ping Scan at 23:08
Scanning 192.168.178.26 [2 ports]
Completed Ping Scan at 23:08, 0.00s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 23:08
Completed Parallel DNS resolution of 1 host. at 23:08, 0.00s elapsed
Initiating Connect Scan at 23:08
Scanning raspberrypi.fritz.box (192.168.178.26) [1000 ports]
Discovered open port 22/tcp on 192.168.178.26
Discovered open port 80/tcp on 192.168.178.26
Discovered open port 9001/tcp on 192.168.178.26
Completed Connect Scan at 23:08, 1.15s elapsed (1000 total ports)
Nmap scan report for raspberrypi.fritz.box (192.168.178.26)
Host is up (0.011s latency).
Not shown: 997 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
9001/tcp open  tor-orport

Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 1.22 seconds

**Habt Ihr eine Idee, warum ich den Port 5001 nicht erreiche?**

**Comment by joewa** [comment]
Ich hatte so eine ähnliche Frage schon in Slack geschrieben.

ufw hab ich noch nie angerührt. Keine Ahnung was das macht.

Ich würde versuchen "die Seite" über den Apache2 zu leiten. Hab aber keine Ahnung, ob das sinnvoll oder überhaupt zielführend ist.

Dann müsste /etc/apache2/sites-enabled/callfordemocracy.conf ungefähr so aussehen:
```
<VirtualHost *:443>
        ServerName cfd.betelgeuse.changeip.net

        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/owncloud.crt
        SSLCertificateKeyFile /etc/apache2/ssl/owncloud.key

        ErrorLog ${APACHE_LOG_DIR}/cfd_betelgeuse_error.log
        CustomLog ${APACHE_LOG_DIR}/cfd_betelgeuse_access.log combined

        ProxyPass / http://127.0.0.1:5001/
        SetEnv proxy-sendchunks 1
        RequestHeader set X-Forwarded-SSL "on"
</VirtualHost>
```

Ich gebe für heute auf, probiere aber die Tage noch ein wenig herum...

**Comment by rickmer** [comment]
ufw ist ein einfacher commandline wrapper iptables also zur Steuerung der linux kernel firewall.
Da incoming und outgoing auf allow eingestellt sind, und zudem regeln installiert sind die port 5001 exponieren sollte die Firewall kein Problem sein. 

Das Problem dürfte sein, dass rephone standardmäßig nur auf localhost auf dem loopback device lauscht. 

Man kann und sollte in einer Produktivumgebung - wie oben beschrieben - mit einem Proxy den localhost:5001 auf port 443 auf einer anderen addresse mit TLS exponieren.

Für Testzwecke kann man auch mit dem Host parameter die ip-addresse übergeben, auf der rephone auf connections lauschen soll.
```
./run.py --host <die.ip.des.raspi>
```
